[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "numpy>=1.20.1",
    "scipy>=1.6.1",
    "scikit-learn>=0.23.2",
    "joblib>=1.0.1",
    "matplotlib>=3.3.4"
]
build-backed = "setuptools.build_meta"